services:
  postgresdb:
    image: pgvector/pgvector:pg17
    container_name: postgresdb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: salesdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d salesdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: